import type { Metadata } from 'next'
// import { Inter } from 'next/font/google' // This is used for fonts
import './globals.css' //  from this you can access global.css file
import Navbar from '../../components/navbar'

// const inter = Inter({ subsets: ['latin'] })// This is used for fonts

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body /*className={inter.className} - inter.classname is used for fonts*/>
      <Navbar/>
        
                {children}
      
      <h1> Footer in Main layout.tsx file </h1>
        </body>
    </html>
  )
}